run:
  deadline: 5m
  go: "1.20"

linters:
  disable-all: true
  enable:
    - errcheck
    - exportloopref
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
  # Run with --fast=false for more extensive checks
  fast: true

linters-settings:
  goimports:
    local-prefixes: github.com/Azure/azure-workload-identity
  gocritic:
    enabled-tags:
    - performance
  lll:
    line-length: 200
  misspell:
    locale: US
  staticcheck:
    go: "1.20"
